/* Generated by wayland-scanner 1.25.0 */

#ifndef XX_CUTOUTS_V1_SERVER_PROTOCOL_H
#define XX_CUTOUTS_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;
struct wl_surface;
struct xx_cutouts_manager_v1;
struct xx_cutouts_v1;

#ifndef XX_CUTOUTS_MANAGER_V1_INTERFACE
#define XX_CUTOUTS_MANAGER_V1_INTERFACE
extern const struct wl_interface xx_cutouts_manager_v1_interface;
#endif
#ifndef XX_CUTOUTS_V1_INTERFACE
#define XX_CUTOUTS_V1_INTERFACE
extern const struct wl_interface xx_cutouts_v1_interface;
#endif

#ifndef XX_CUTOUTS_MANAGER_V1_ERROR_ENUM
#define XX_CUTOUTS_MANAGER_V1_ERROR_ENUM
enum xx_cutouts_manager_v1_error {
	XX_CUTOUTS_MANAGER_V1_ERROR_INVALID_ROLE = 0,
	XX_CUTOUTS_MANAGER_V1_ERROR_DEFUNCT_CUTOUTS_OBJECT = 1,
};
#endif /* XX_CUTOUTS_MANAGER_V1_ERROR_ENUM */

struct xx_cutouts_manager_v1_interface {
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	void (*get_cutouts)(struct wl_client *client,
			    struct wl_resource *resource,
			    uint32_t id,
			    struct wl_resource *surface);
};

#define XX_CUTOUTS_MANAGER_V1_DESTROY_SINCE_VERSION 1
#define XX_CUTOUTS_MANAGER_V1_GET_CUTOUTS_SINCE_VERSION 1

#ifndef XX_CUTOUTS_V1_TYPE_ENUM
#define XX_CUTOUTS_V1_TYPE_ENUM
enum xx_cutouts_v1_type {
	XX_CUTOUTS_V1_TYPE_CUTOUT = 0,
	XX_CUTOUTS_V1_TYPE_NOTCH = 1,
	XX_CUTOUTS_V1_TYPE_WATERFALL = 2,
};
#endif /* XX_CUTOUTS_V1_TYPE_ENUM */

#ifndef XX_CUTOUTS_V1_CORNER_POSITION_ENUM
#define XX_CUTOUTS_V1_CORNER_POSITION_ENUM
enum xx_cutouts_v1_corner_position {
	XX_CUTOUTS_V1_CORNER_POSITION_TOP_LEFT = 0,
	XX_CUTOUTS_V1_CORNER_POSITION_TOP_RIGHT = 1,
	XX_CUTOUTS_V1_CORNER_POSITION_BOTTOM_RIGHT = 2,
	XX_CUTOUTS_V1_CORNER_POSITION_BOTTOM_LEFT = 3,
};
#endif /* XX_CUTOUTS_V1_CORNER_POSITION_ENUM */

#ifndef XX_CUTOUTS_V1_ERROR_ENUM
#define XX_CUTOUTS_V1_ERROR_ENUM
enum xx_cutouts_v1_error {
	XX_CUTOUTS_V1_ERROR_INVALID_ELEMENT_ID = 0,
};
#endif /* XX_CUTOUTS_V1_ERROR_ENUM */

struct xx_cutouts_v1_interface {
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	void (*set_unhandled)(struct wl_client *client,
			      struct wl_resource *resource,
			      struct wl_array *unhandled);
};

#define XX_CUTOUTS_V1_CUTOUT_BOX 0
#define XX_CUTOUTS_V1_CUTOUT_CORNER 1
#define XX_CUTOUTS_V1_CONFIGURE 2

#define XX_CUTOUTS_V1_DESTROY_SINCE_VERSION 1
#define XX_CUTOUTS_V1_SET_UNHANDLED_SINCE_VERSION 1
#define XX_CUTOUTS_V1_CUTOUT_BOX_SINCE_VERSION 1
#define XX_CUTOUTS_V1_CUTOUT_CORNER_SINCE_VERSION 1
#define XX_CUTOUTS_V1_CONFIGURE_SINCE_VERSION 1

static inline void
xx_cutouts_v1_send_cutout_box(struct wl_resource *resource_, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t type, uint32_t id)
{
	wl_resource_post_event(resource_, XX_CUTOUTS_V1_CUTOUT_BOX, x, y, width, height, type, id);
}

static inline void
xx_cutouts_v1_send_cutout_corner(struct wl_resource *resource_, uint32_t position, uint32_t radius, uint32_t id)
{
	wl_resource_post_event(resource_, XX_CUTOUTS_V1_CUTOUT_CORNER, position, radius, id);
}

static inline void
xx_cutouts_v1_send_configure(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, XX_CUTOUTS_V1_CONFIGURE);
}

#ifdef  __cplusplus
}
#endif

#endif
